import "./globals.css";
import type { Metadata } from "next";
import { Inter, Inconsolata } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const inconsolata = Inconsolata({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inconsolata",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${inconsolata.variable} scroll-smooth`}
		>
			<body className="font-inter overflow-x-hidden text-secondary-foreground">
				{children}
			</body>
		</html>
	);
}
